// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT7OoRZgG0ObNcZgJdMrY2LRFpTS6iIxo',
    appId: '1:920832673637:web:ef95e7357bc6684a2d838c',
    messagingSenderId: '920832673637',
    projectId: 'speed-services-a',
    authDomain: 'speed-services-a.firebaseapp.com',
    storageBucket: 'speed-services-a.firebasestorage.app',
    measurementId: 'G-SJ929LFXX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDivU1Cb99kx94QdcH1xHvanZDi3U0gsTg',
    appId: '1:920832673637:android:e0ecde014a2220be2d838c',
    messagingSenderId: '920832673637',
    projectId: 'speed-services-a',
    storageBucket: 'speed-services-a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOUu-LYPVrcU5WgF6UFc1GN3G0-v-fO0E',
    appId: '1:920832673637:ios:614f76c008c3b0d42d838c',
    messagingSenderId: '920832673637',
    projectId: 'speed-services-a',
    storageBucket: 'speed-services-a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOUu-LYPVrcU5WgF6UFc1GN3G0-v-fO0E',
    appId: '1:920832673637:ios:614f76c008c3b0d42d838c',
    messagingSenderId: '920832673637',
    projectId: 'speed-services-a',
    storageBucket: 'speed-services-a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT7OoRZgG0ObNcZgJdMrY2LRFpTS6iIxo',
    appId: '1:920832673637:web:20c281339fb1ddc52d838c',
    messagingSenderId: '920832673637',
    projectId: 'speed-services-a',
    authDomain: 'speed-services-a.firebaseapp.com',
    storageBucket: 'speed-services-a.firebasestorage.app',
    measurementId: 'G-X41ZS4G9M6',
  );
}
